name: Python Check

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Compile project
        run: python -m compileall main.py ui data services models
